Feature/http port
0xProject/0x-launch-kit-backend pull request #14
Opened 2018-11-17 02:50 UTC by chrisabrams

The default server port is 3000 but when developing sometimes changing the port in the config is not an available option. Defining the environment variable `HTTP_PORT` is another option.

2018-11-17 17:25 UTC, fabioberger requested changes

2018-11-17 17:25 UTC, fabioberger commented on js/config.js
> +exports.HTTP_PORT = process.env.HTTP_PORT || 3000;
@chrisabrams can we make `HTTP_PORT` and config exported from `config.ts`? We've opted for keeping all configurations in that one place, rather then splitting between there and environment variables.

2018-11-17 17:25 UTC, fabioberger commented on README.md
> +
Once this is moved to `config.ts`, we can add this setting to the `config` step above.

2018-11-17 17:25 UTC, fabioberger commented on yarn.lock
> +  resolved "http://localhost:4873/0x.js/-/0x.js-1.0.8.tgz#779d0d394ba3e4519a980b1035864f87297b0d52"
Looks like you're using a local registry, however you cannot push these changes since other dev's don't have your local setup.

2018-11-20 11:11 UTC, LogvinovLeon requested changes

2018-11-20 11:11 UTC, LogvinovLeon commented on js/config.js
> +exports.HTTP_PORT = process.env.HTTP_PORT || 3000;
I agree that those simple configs that can be configured over ENV variables might be done so.

2018-11-20 11:11 UTC, LogvinovLeon commented on README.md
> +
You shouldn't call this section `Server Port` There would be other env configs in the future. Let's call it Configuration and describe that you can configure everything via config.ts or override it with env vars

2018-12-06 04:51 UTC, dekz commented
Needed this and a bit more for my own needs, opened #21.

2018-12-06 04:51 UTC, closed without merging