Add error handling and networkId parsing middlewares
0xProject/0x-launch-kit-backend pull request #3
Opened 2018-09-28 13:32 UTC by LogvinovLeon

2018-09-28 13:53 UTC, fabioberger requested changes

2018-09-28 13:53 UTC, fabioberger commented on ts/src/errors.ts
> +export const generalErrorCodesReasons: { [key in GeneralErrorCodes]: string } = {
Let's try and start using the convention `to` for mappings: `generalErrorCodeToReason`

2018-09-28 13:53 UTC, fabioberger commented on ts/src/errors.ts
> +    THROTTLED = 103,
Convention: camel-case key values.

2018-09-28 13:53 UTC, fabioberger commented on ts/src/middleware/error_handling.ts
> +                res.status(relayerError.statusCode).send(errorBody);
Let's `return` here.

2018-09-28 13:53 UTC, fabioberger commented on ts/src/middleware/url_params_parsing.ts
> +        return NETWORK_ID;
Rename to `DEFAULT_NETWORK_ID`

2018-09-28 13:53 UTC, fabioberger commented on ts/src/middleware/url_params_parsing.ts
> +            const validationErroItem = {
Typo: `Erro`

2018-10-01 11:42 UTC, fabioberger approved these changes

2018-10-01 11:42 UTC, fabioberger commented on package.json
> +        "@0xproject/order-watcher": "^2.0.0",
Latest version of all packages has changed. Order-watcher is now `2.1.0` for example. Not sure it's worth upgrading yet, but maybe at the end.

2018-10-01 11:42 UTC, fabioberger commented on ts/src/middleware/url_params_parsing.ts
> +    req.networkId = networkId;
Add a `// HACK:` comment here and explain that this is the recommended way of passing data, despite it not being type-safe and hacky. Source link would be nice too.

2018-10-01 12:17 UTC, LogvinovLeon commented on package.json
> +        "@0xproject/order-watcher": "^2.0.0",
I'll upgrade them as I need those new features and at the end.

2018-10-01 12:17 UTC, LogvinovLeon commented on ts/src/middleware/url_params_parsing.ts
> +    req.networkId = networkId;
It's hacky, but type safe in a way. I overrode the type of Request in globals and it now has that property. So after the middleware - the code is type-safe.

2018-10-01 12:20 UTC, merged