use unique id as default fee recipient
0xProject/0x-launch-kit-backend pull request #42
Opened 2019-02-01 05:55 UTC by xianny

This resolves https://app.asana.com/0/973912100782313/982982542765688/f

Add a default fee_recipient_address if none is specified. The address uniquely identifies each instance of launch kit and persists on restart.

I edited the README to reflect that we use env variables and created a .env file with default keys. The intended workflow is that developers will edit the .env file and mostly leave the config files alone.

## Testing

In this order:
```
yarn start:ts
yarn build && yarn start:ts
<edit .env file to specific fee recipient>
yarn start:ts
<edit .env file to remove fee recipient>
yarn start:ts
```

Read the logs, each run should have the same default fee recipient.

2019-02-01 07:20 UTC, dekz requested changes

2019-02-01 07:20 UTC, dekz commented on ts/src/config.ts
> +    ? new BigNumber(_.parseInt(process.env.TAKER_FEE_ZRX_UNIT_AMOUNT as string))
Since these are Unit amounts (not base unit amounts) a user should be able to pass in `TAKER_FEE_ZRX_UNIT_AMOUNT="1.234"`. `_.parseInt` will truncate the decimals

2019-02-01 07:20 UTC, dekz commented on ts/src/config.ts
> +export const NETWORK_ID = !_.isEmpty(process.env.NETWORK_ID) ? _.parseInt(process.env.NETWORK_ID as string) : 42;
Now that we have the `.env` file, should we put the defaults live there?
```
// .env
NETWORK_ID=42
```

2019-02-01 07:20 UTC, dekz commented on ts/src/config.ts
> +    if (existingDefault === '') {
```suggestion
    if (_.isEmpty(existingDefault)) {
```

2019-02-01 07:20 UTC, dekz commented on ts/src/config.ts
> +    if (existingDefault === '') {
I would localise reading of `metadata` into here as it's not used anywhere else (until it makes sense to put it up higher)

2019-02-01 07:20 UTC, dekz commented on ts/src/config.ts
> +        fs.writeFileSync(metadataPath, JSON.stringify(metadataCopy));
```suggestion
        fs.writeFileSync(metadataPath, JSON.stringify(metadataCopy, null, 2));
```
So it's a bit easier to edit. Or maybe add it to prettier

2019-02-04 07:25 UTC, xianny commented on ts/src/config.ts
> +export const NETWORK_ID = !_.isEmpty(process.env.NETWORK_ID) ? _.parseInt(process.env.NETWORK_ID as string) : 42;
Not sure. It would simplify the code, but then we would have defaults spread across two files. Do you feel strongly either way? Happy to implement whichever.

2019-02-04 12:30 UTC, fabioberger requested changes

2019-02-04 12:30 UTC, fabioberger commented on .gitignore
> +# .env
These won't actually be ignored if they have a `#` in-front of them.

2019-02-04 12:30 UTC, fabioberger commented on README.md
> +-   `FEE_RECIPIENT` -- (optional) The Ethereum address which should be specified as the fee recipient in orders your relayer accepts, optional.
```suggestion
-   `FEE_RECIPIENT` -- (optional) The Ethereum address which should be specified as the fee recipient in orders your relayer accepts, optional. Defaults to a fake address that helps the 0x core team collect anonymous, non-invasive telemetry on Launch Kit developer usage.
```

2019-02-04 12:30 UTC, fabioberger commented on ts/src/config.ts
> +    '0xd0a1e359811322d97991e03f863a0c30c2cf029c', // WETH
```suggestion
    '0xd0a1e359811322d97991e03f863a0c30c2cf029c', // WETH on Kovan
```

2019-02-04 12:30 UTC, fabioberger commented on ts/src/config.ts
> +    '0x2002d3812f58e35f0ea1ffbf80a75a38c32175fa', // ZRX
```suggestion
    '0x2002d3812f58e35f0ea1ffbf80a75a38c32175fa', // ZRX on Kovan
```

2019-02-04 12:30 UTC, fabioberger commented on ts/src/config.ts
> +    ? (process.env.FEE_RECIPIENT as string)
We aren't doing any validation on the values fed into Launch Kit via ENV Vars. I think we should. Otherwise we don't know if they supplied a valid Ethereum address, and it will fail in unexpected ways. We could use `@0x/assert` here.

2019-02-04 12:30 UTC, fabioberger commented on ts/src/config.ts
> +    ? (process.env.FEE_RECIPIENT as string)
I'm imagining a method similar to this:

```
function assertEnvVarType(name: string, value: any, expectedType: EnvVarTypes): void {
  switch (expectedType) {
    case EnvVarTypes.String:
      assert.isString(name, value);
      return;
    case EnvVarTypes.EthAddress:
      assert.isETHAddressHex(name, value);
      return;
    ...
    default:
      throw new Error(`Unrecognized EnvVarTypes: ${expectedType} encountered for variable ${name}.`);
  }
}
```

2019-02-04 12:30 UTC, fabioberger commented on .env
> +RPC_URL=
What is the "order of operations" for env vars. Do those supplied in-line before a bash command take precedence over boths in the `.env` file?

2019-02-04 12:30 UTC, fabioberger commented on ts/typings.d.ts
> +}
This should not be necessary anymore. We just need to add `"resolveJsonModule": true,` to `tsconfig.json`. See: https://stackoverflow.com/questions/49996456/importing-json-file-in-typescript

2019-02-04 14:01 UTC, xianny commented on ts/typings.d.ts
> +}
whoops, this was leftover from when I was importing the json file as a module. removing.

2019-02-04 14:10 UTC, xianny commented on .env
> +RPC_URL=
The environment always has precedence. The .env file variable will be skipped if there's collision

2019-02-04 15:05 UTC, xianny commented on ts/src/config.ts
> +    ? (process.env.FEE_RECIPIENT as string)
good idea! will implement.

2019-02-04 15:08 UTC, xianny commented on ts/src/config.ts
> +export const NETWORK_ID = !_.isEmpty(process.env.NETWORK_ID) ? _.parseInt(process.env.NETWORK_ID as string) : 42;
I added type validations for the env variables and now I think we should keep the defaults in the config file. That way, even if a developer supplies bad values in the .env file, working defaults are hardcoded into the config. It will still throw an error if there are bad values in the .env file, but will fallback to defaults if the values in .env are left blank.

2019-02-04 15:12 UTC, fabioberger requested changes

2019-02-04 15:12 UTC, fabioberger commented on metadata.json
> +{"DEFAULT_FEE_RECIPIENT":"0xABCABCe1cd17d6f6323fd89979e9c1ce082000ed"}
I'd rather we generate a unique address per Launch Kit developer that get's generated and stored the first time it's run.

2019-02-04 15:22 UTC, xianny commented on metadata.json
> +{"DEFAULT_FEE_RECIPIENT":"0xABCABCe1cd17d6f6323fd89979e9c1ce082000ed"}
oooops. yep, this is not meant to be here. thanks for catching!

2019-02-04 15:34 UTC, fabioberger requested changes

2019-02-04 15:34 UTC, fabioberger commented on README.md
> +
Why the new line?

2019-02-04 15:34 UTC, fabioberger commented on README.md
> +-   `FEE_RECIPIENT` -- The Ethereum address which should be specified as the fee recipient in orders your relayer accepts. Defaults to a fake address that helps the 0x core team collect anonymous, no
```suggestion
-   `FEE_RECIPIENT` -- The Ethereum address which should be specified as the fee recipient in orders your relayer accepts. Defaults to a fake address that helps the 0x core team collect anonymous, already public data on Launch Kit developer usage.
```

2019-02-04 15:34 UTC, fabioberger commented on ts/src/config.ts
> +            return parseInt(value, 10);
Nit: not loving how we call `parseInt` on `value` three times. Can we do it once and reference?

2019-02-04 15:34 UTC, fabioberger commented on ts/src/config.ts
> +                if (new BigNumber(parseFloat(value)).isNegative) {
Why parse float? Unit amounts should be integers.

2019-02-04 15:37 UTC, xianny commented on ts/src/config.ts
> +                if (new BigNumber(parseFloat(value)).isNegative) {
I am still not entirely sure of the terminology but I believe these are units of ZRX, not base units (wei...?) and should be able to have decimals. @dekz seemed [pretty sure](https://github.com/0xProject/0x-launch-kit/pull/42#discussion_r252949881)

2019-02-04 15:52 UTC, xianny commented on README.md
> +
Weird. I ran it through a previewer and made all the newlines and idents consistent.

2019-02-04 15:56 UTC, fabioberger approved these changes

2019-02-04 16:02 UTC, merged

2019-02-04 23:19 UTC, dekz commented on ts/src/config.ts
> +                if (new BigNumber(parseFloat(value)).isNegative) {
BigNumber can handle strings (with decimals) as input.