Update Dockerfile
0xProject/0x-launch-kit-backend pull request #54
Opened 2019-03-13 19:15 UTC by pointtoken

This creates a much smaller final docker image. Also uses pm2 instead of forever.

2019-03-18 19:46 UTC, ericramos1980 approved these changes

2019-03-20 13:23 UTC, fabioberger requested changes

2019-03-20 13:23 UTC, fabioberger commented on Dockerfile
> +FROM node:11.1.0 as build-machine
Why not just use `alpine-node` here?

2019-03-20 13:23 UTC, fabioberger commented on Dockerfile
> +RUN npm install pm2 -g
Why is `pm2` better then `forever`?

2019-03-20 17:04 UTC, pointtoken commented on Dockerfile
> +RUN npm install pm2 -g
https://ifelse.io/2015/09/02/running-node.js-apps-in-production/

2019-04-06 04:05 UTC, pointtoken commented on Dockerfile
> +FROM node:11.1.0 as build-machine
There are requirements for the build that necessitate that complete node docker image.

2019-06-28 08:23 UTC, dekz commented
Fixing this in #65.

2019-06-28 08:23 UTC, closed without merging