(Fix) - Sort orderbook by price
0xProject/0x-launch-kit-backend pull request #56
Opened 2019-03-26 16:38 UTC by mariano-aguero

Closes #41 

Implements the sorting of bids/asks for the `GET /v2/orderbook` endpoint as stated in the SRA v2:
https://github.com/0xProject/standard-relayer-api/blob/master/http/v2.md#get-v2orderbook

- Sort bids in descending order by price: `takerAssetAmount/makerAssetAmount`.
- Sort asks in ascending order by price: `makerAssetAmount/takerAssetAmount`.
- The orders are further sorted by taker fee price. After taker fee price, orders are to be sorted by expiration in ascending order.

2019-03-26 22:50 UTC, fabioberger requested changes
Thanks for the PR! Could you also please minor bump the package's version in `package.json` and add an entry in `CHANGELOG.md`?

2019-03-26 22:50 UTC, fabioberger commented on ts/src/orderbook.ts
> +const compareOrder = (orderA: SignedOrder, orderB: SignedOrder): number => {
Let's rename this to `compareOrderByFeeRatio` as it better describes what this method is doing.

2019-03-27 09:19 UTC, LogvinovLeon approved these changes

2019-03-27 12:32 UTC, mariano-aguero commented on ts/src/orderbook.ts
> +const compareOrder = (orderA: SignedOrder, orderB: SignedOrder): number => {
> Let's rename this to `compareOrderByFeeRatio` as it better describes what this method is doing.

Thanks for the feedback! Done here https://github.com/0xProject/0x-launch-kit/pull/56/commits/7e55f27e0b969967cb0e9b9d67b81e0a313a8a51 . 

Regards

2019-03-27 12:49 UTC, mariano-aguero commented
> Thanks for the PR! Could you also please minor bump the package's version in `package.json` and add an entry in `CHANGELOG.md`?

Thanks for the feedback! The version was updated (`yarn version --minor`) and also added an entry in the `CHANGELOG.md`. 

Regards

2019-03-27 18:39 UTC, fabioberger approved these changes

2019-03-27 18:39 UTC, merged