Filters, pagination, Dockerfile, Order Watcher
0xProject/0x-launch-kit-backend pull request #6
Opened 2018-11-07 10:57 UTC by LogvinovLeon

* Adds Dockerfile and deployment instructions
* Improves the README
* Adds filters on orders endpoint
* Improves pagination
* Adds order watcher to stack and shadows invalid orders

2018-11-09 12:48 UTC, fabioberger requested changes

2018-11-09 12:48 UTC, fabioberger commented on Dockerfile
> +CMD [ "yarn", "start:ts" ]
If any error is encountered, this process will simply die. We should use `forever` to re-start it if it fails. See testnet-faucet Dockerfile.

2018-11-09 12:48 UTC, fabioberger commented on README.md
> +# 0x-launch-kit
Is this the launch kit?

2018-11-09 12:48 UTC, fabioberger commented on README.md
> +-   delete the TS directory
```suggestion
-   delete the `ts` directory
```

2018-11-09 12:48 UTC, fabioberger commented on README.md
> +-   Look through the JS code and start modifying it. It was auto-generated from TS code so it might not be pretty, but it should be pretty easy to get it into good shape
```suggestion
-   Look through the JS code and start modifying it. It was auto-generated from TS code and we tried our best to make it readable. It might require some improving and should provide a good starting point.
```

2018-11-09 12:48 UTC, fabioberger commented on README.md
> +-   delete the JS directory
```suggestion
-   delete the `js` directory
```

2018-11-09 12:48 UTC, fabioberger commented on README.md
> +We use [typeorm](https://github.com/typeorm/typeorm) as an ORM. It allows us to migrate to other data sources later and makes the code cleaner.
```suggestion
This project uses [typeorm](https://github.com/typeorm/typeorm). It makes it easier for anyone to switch out the backing database that this project uses.
```

2018-11-09 12:48 UTC, fabioberger commented on README.md
> +As for now this project uses sqlite backend.
This shouldn't be on it's own line. This whole section can be a sentence.

2018-11-09 12:48 UTC, fabioberger commented on README.md
> +`0x-launch-kit` ships as a docker container. To build the image run:
```suggestion
`0x-launch-kit` ships as a docker container.  First, install Docker ([mac](https://docs.docker.com/docker-for-mac/install/), [windows](https://docs.docker.com/docker-for-windows/install/)). To build the image run:
```

2018-11-09 12:48 UTC, fabioberger commented on README.md
> +Chack that it's working by running
```suggestion
Check that it's working by running
```

2018-11-09 12:48 UTC, fabioberger commented on README.md
> +## Deploying
Before this section, let's add a section about how to develop this project further. Explain all the command they can run that are in `package.json` (e.g lint, tests, build, clean). Put this section near the top.

2018-11-09 12:48 UTC, fabioberger commented on package.json
> +        "@0x/typescript-typings": "^3.0.3",
🚀

2018-11-09 12:48 UTC, fabioberger commented on ts/src/config.ts
>  // TODO(leo): Load those from config.
Please address this.

2018-11-09 12:48 UTC, fabioberger commented on README.md
> +
We should also have a section describing the config file, and what are all the parameters that are configurable in this project.

2018-11-09 12:48 UTC, fabioberger commented on ts/src/config.ts
> +export const NETWORK_ID = Number(process.env.NETWORK_ID) || DEFAULT_NETWORK_ID;
Hm, let's create a `configs.json` file and use that for all configurations. Let's not do some things via ENV vars, and others via json, that get's confusing.

2018-11-09 12:48 UTC, fabioberger commented on ts/src/handlers.ts
> +        const perPage = _.isUndefined(req.query.perPage) ? DEFAULT_PER_PAGE : Number(req.query.perPage);
Can the caller really specify _any_ `perPage` value? Thought there was an upper-bound of 100...

2018-11-09 12:48 UTC, fabioberger commented on ts/src/handlers.ts
> +        if (assetPairsStore.contains(signedOrder.makerAssetData, signedOrder.takerAssetData)) {
Let's stick with using `_.includes`

2018-11-09 12:48 UTC, fabioberger commented on ts/src/orderbook.ts
> +        orderWatcher.addOrderAsync(signedOrder);
We should `await` this no?

2018-11-09 12:48 UTC, fabioberger commented on ts/src/orderbook.ts
> +            records: bidApiOrders.slice(page * perPage, (page + 1) * perPage),
This logic is repeated in many places, let's make a utility function that does this.

2018-11-09 12:48 UTC, fabioberger commented on ts/src/orderbook.ts
> +orderWatcher.subscribe(orderBook.onOrderStateChangeCallback);
Where is the process that prunes orders out of the `shadowedOrders` set? Without this, it will grow indefinitely and slow down queries.

2018-11-09 12:48 UTC, fabioberger commented on ts/src/schemas/order_config_request_schema.ts
> +        takerAssetAmount: { $ref: '/numberSchema' },
Why isn't this schema in `@0x/json-schema`? Also, this should be `wholeNumberSchema`, which was properly fixed in `@0x/json-schema`...

2018-11-09 14:46 UTC, LogvinovLeon commented on README.md
> +# 0x-launch-kit
Yes

2018-11-12 13:58 UTC, LogvinovLeon commented on ts/src/handlers.ts
> +        if (assetPairsStore.contains(signedOrder.makerAssetData, signedOrder.takerAssetData)) {
It's not an array method. It's a custom method on a custom class. I'll rename it to includes.

2018-11-12 16:57 UTC, fabioberger requested changes

2018-11-12 16:57 UTC, fabioberger commented on README.md
>  This is a template 0x relayer. It's customizable, open source and completely free to use. You can just fork it and start modifying it for your own needs.
```suggestion
This is a template 0x relayer. It's customizable, open-source and completely free to use. You can fork it and customize it to fix your own needs.
```

2018-11-12 16:57 UTC, fabioberger commented on README.md
>  It ships as both a typescript and javascript module. TS sources are in the `ts` directory while auto-generated JS sources are in the `js` directory.
```suggestion
It ships as both a typescript and javascript module. Typescript sources are in the `ts` directory while auto-generated Javascript sources are in the `js` directory.
```

2018-11-12 16:57 UTC, fabioberger commented on README.md
> +If you want to work on it as a JS project:
```suggestion
If you want to work on it in Javascript:
```

2018-11-12 16:57 UTC, fabioberger commented on README.md
> +If you want to work on it as a TS project:
```suggestion
If you want to work on it in Typescript:
```

2018-11-12 16:57 UTC, fabioberger commented on README.md
> +-   Look through the JS code and start modifying it. It was auto-generated from TS code and we tried our best to make it readable. It might require some improving and should provide a good starting p
```suggestion
-   Look through the Javascript code and start modifying it. It was auto-generated from Typescript code and we tried our best to make it readable. It might require some improving and should provide a good starting point.
```

2018-11-12 16:57 UTC, fabioberger commented on README.md
> +-   prettier:ts - Prettifies `TS` code
Let's split these into TS & JS commands.

2018-11-12 16:57 UTC, fabioberger commented on README.md
> +This project uses [typeorm](https://github.com/typeorm/typeorm). It makes it easier for anyone to switch out the backing database that this project uses. As for now this project uses sqlite backend.
```suggestion
This project uses [typeorm](https://github.com/typeorm/typeorm). It makes it easier for anyone to switch out the backing database that this project uses. As for now this project uses an [SQLite](https://sqlite.org/docs.html) backend. Because we support both Javascript and Typescript codebases, we don't use decorators. TypeORM shines with decorators, so you might want to use them if you're going to be working in Typescript.
```

2018-11-12 16:57 UTC, fabioberger commented on README.md
> +Launch kit can be configured by changing the config variables in the [config.json](config.json) file.
```suggestion
0x Launch kit can be configured by changing the config variables in the [config.json](config.json) file.
```

2018-11-12 16:57 UTC, fabioberger commented on README.md
> +You can check that the image is built running
```suggestion
You can check that the image was built by running:
```

2018-11-12 16:57 UTC, fabioberger commented on config.json
> +    "NETWORK_ID": 50,
By default does this also spin up Ganache? If you are using mainnet Infura below, shouldn't this be "1"?

2018-11-12 16:57 UTC, fabioberger commented on config.json
> +        "0xa2b31dacf30a9c50ca473337c01d8a201ae33e32"
Let's just have one here.

2018-11-12 16:57 UTC, fabioberger commented on config.json
> +                "assetData": "0x0257179264389b814a946f3e92105513705ca6b990"
What assets are these?

2018-11-12 16:57 UTC, fabioberger commented on config.json
> +    "PERMANENT_CLEANUP_INTERVAL": 10000,
```suggestion
    "PERMANENT_CLEANUP_INTERVAL_MS": 10000,
```

2018-11-12 16:57 UTC, fabioberger commented on config.json
> +    "ORDER_SHADOWING_MARGIN": 100000,
```suggestion
    "ORDER_SHADOWING_MARGIN_MS": 100000,
```

2018-11-12 16:57 UTC, fabioberger commented on package.json
> +        "@0x/typescript-typings": "^3.0.3",
Update all these to the latest versions.

2018-11-12 16:57 UTC, fabioberger commented on config.json
> +{
If we make this a `.ts`/`.js` file, we can add comments explaining the various configs. I think that's worth it for a starter project. Thoughts?

2018-11-12 18:10 UTC, LogvinovLeon commented on config.json
> +                "assetData": "0x0257179264389b814a946f3e92105513705ca6b990"
Some example assets. I don't even know. I think it should be empty. We should convert that to a js file and comment them out.

2018-11-12 18:29 UTC, fabioberger approved these changes

2018-11-12 18:32 UTC, merged