[WIP] Support Mesh and OrderWatcher
0xProject/0x-launch-kit-backend pull request #67
Opened 2019-07-02 09:04 UTC by dekz

Allowing a smooth transition from OrderWatcher to Mesh.

A user can supply the following ENV vars to enable Mesh when ready. In a future release we will deprecate OrderWatcher and remove it entirely. User is able to quickly switch back in the event of unexpected errors.

ENV Vars
```
USE_MESH=true
MESH_ENDPOINT=ws://localhost:60557
```

2019-07-27 09:43 UTC, fabioberger requested changes

2019-07-27 09:43 UTC, fabioberger commented on ormconfig.json
> +    "logger": "debug",
Do we want to leave this in?

2019-07-27 09:43 UTC, fabioberger commented on ts/src/handlers.ts
> +            utils.log(e);
When do we expect this case to be hit?

2019-07-27 09:43 UTC, fabioberger commented on ts/src/order_watchers/mesh_adapter.ts
> +                    break;
Why doesn't this result in the order being `added`?

2019-07-27 09:43 UTC, fabioberger commented on ts/src/order_watchers/mesh_adapter.ts
> +                case OrderEventKind.FillabilityIncreased:
`FillabilityIncreased` can happen due to block re-orgs. It can go from `0` -> `X` but also from `X` -> `Y` which would not mean that it was "added".

2019-07-27 09:43 UTC, fabioberger commented on ts/src/order_watchers/order_watcher_adapter.ts
> +            } else {
Nit: If you return after `utils.log(err);`, you can omit the `else` nesting.

2019-07-27 09:43 UTC, fabioberger commented on ts/src/orderbook.ts
> +            await this.addExistingOrdersToOrderWatcherAsync();
You also want to add all Mesh orders into the DB. Does this method do that too?

2019-07-27 09:43 UTC, fabioberger commented on ts/src/orderbook.ts
> +            throw new Error(rejected[0].message);
This looks a bit strange to me. Why are we just throwing the first rejected message?

2019-07-27 09:43 UTC, fabioberger commented on ts/src/orderbook.ts
> +        const getOrdersPromise = this._orderWatcher.getOrdersAsync();
Why are we declaring this here it only used in one place below. Let's in-line.

2019-07-27 09:43 UTC, fabioberger commented on ts/src/utils.ts
> +    },
These are identical functions, keep one and remove the other.

2019-07-27 09:43 UTC, fabioberger commented on ts/src/utils.ts
> +        opts: { interval: number; maxRetries: number } = { interval: 5000, maxRetries: 10 },
These seem like pretty generous defaults. So the code could get stuck attempting an async call for almost a minute? Think we should reduce that upperbound.

2019-07-27 09:48 UTC, dekz commented on ts/src/utils.ts
> +        opts: { interval: number; maxRetries: number } = { interval: 5000, maxRetries: 10 },
Yeah definitely, these were defaults from when I used the code in pulling from SRA endpoints and getting backoffs. I'll lower to something more aligned with Mesh performance

2019-07-27 09:49 UTC, dekz commented on ts/src/orderbook.ts
> +        const getOrdersPromise = this._orderWatcher.getOrdersAsync();
We're kicking them off concurrently, not a HUGE performance gain but helps on startup boot with 500+ orders.

2019-07-27 10:05 UTC, dekz commented on ts/src/order_watchers/mesh_adapter.ts
> +                    break;
Would this be the first time we've seen this order? I.e Mesh should've pinged us prior to this with an `Added`? This is kept separate atm because we'll later ping updates and store the filledAmount in the db

2019-07-27 10:06 UTC, dekz commented on ts/src/utils.ts
> +    },
Oh yep the sleep is totally no longer used. Thanks

2019-07-27 10:08 UTC, dekz commented on ts/src/orderbook.ts
> +            throw new Error(rejected[0].message);
SRA only supports single orders POST at the moment and this function reflects that. Mesh and Adapted OrderWatcher support arrays of orders. We should update SRA to include a multi post endpoint (good for market makers I assume as well)

2019-07-27 10:09 UTC, dekz commented on ts/src/handlers.ts
> +            utils.log(e);
Never anymore with attempts and reconnects. Will remove

2019-07-27 10:11 UTC, dekz commented on ormconfig.json
> +    "logger": "debug",
Yep this is just indicating to use the `debug` npm package for debug logging, its not an additional verbosity level. For debugging a user can now enable all `DEBUG="*"` or selectively `DEBUG=typeorm:*` or everything but typeorm `DEBUG=*,-typeorm:*`

2019-07-27 10:14 UTC, dekz commented on ts/src/orderbook.ts
> +            await this.addExistingOrdersToOrderWatcherAsync();
Yep, it follows the fool proof pattern of:
1. Send all Orders to Mesh
2. Remove all rejected orders from db
3. Request all orders from Mesh
4. Add all Mesh orders to DB

2019-07-27 10:17 UTC, dekz commented on ts/src/order_watchers/mesh_adapter.ts
> +                case OrderEventKind.FillabilityIncreased:
Since Mesh is watching this order, will an `Unfillable->Added` event occur when it was "shadowed" for lack of fillability, then unshadowed when funds appear? Or will Mesh only return a `FillabilityIncreased` in this case?

2019-08-06 02:23 UTC, dekz commented on ts/src/order_watchers/mesh_adapter.ts
> +                case OrderEventKind.FillabilityIncreased:
This is now coming in via `Updated` and the `remainingFillableTakerAssetAmount` will be updated.

2019-08-06 02:26 UTC, dekz commented on ts/src/order_watchers/mesh_adapter.ts
> +                    break;
This is now handled via `Updated` which will update the `remainingFillableTakerAssetAmount` in the database.

2019-12-04 21:08 UTC, merged