[Feature] Websocket SRA
0xProject/0x-launch-kit-backend pull request #71
Opened 2019-07-25 13:40 UTC by dekz

2019-07-27 10:08 UTC, fabioberger requested changes

2019-07-27 10:08 UTC, fabioberger commented on ts/src/websocket.ts
> +import { assetDataUtils } from '@0x/order-utils';
Let's name the file identical to the class. `websocket_sra.ts`

2019-07-27 10:08 UTC, fabioberger commented on ts/src/websocket.ts
> +    pongInterval: 30000,
Is this for a `ping`/`pong` frame to be sent in order to ensure that the connection is still alive? If so, for Mesh WS, we send one every 5sec. Why was 30sec chosen here?

2019-07-27 10:08 UTC, fabioberger commented on ts/src/websocket.ts
> +        return new WebsocketSRA(server, opts);
This seems like an unnecessary function. Why?

2019-07-27 10:08 UTC, fabioberger commented on ts/src/websocket.ts
> +            ws.ping();
Can you add a comment to this method? Is this simply pruning dead WS connections?

2019-07-27 10:08 UTC, fabioberger commented on ts/src/websocket.ts
> +        ws.send(err.message);
Can SRA clients handle receiving simple string messages? Looks like this isn't specified in the standard. Is this how Radar does it?

2019-07-27 10:08 UTC, fabioberger commented on ts/src/websocket.ts
> +                        ws.send(JSON.stringify({ ...response, payload: [order], requestId }));
This could be made more efficient by batch sending multiple orders that fit a subscription. Why not first create a mapping from `subscriptionOpts` to `orders` and then call `ws.send` once per `subscriptionOpts`?

2019-07-27 10:08 UTC, fabioberger commented on ts/src/websocket.ts
> +        // TODO handle MAP
```suggestion
        // TODO(dekz) handle MAP
```

2019-07-27 10:08 UTC, fabioberger commented on ts/src/websocket.ts
> +        // takerAssetProxyId?: string;
Are these still outstanding?

2019-07-27 10:08 UTC, fabioberger commented on ts/src/websocket.ts
> +        // TODO handle MAP
Can you elaborate on what needs to be done to support MAP?

2019-07-27 10:28 UTC, dekz commented on ts/src/websocket.ts
> +        // TODO handle MAP
Just need to think about this deeper. I don't think people expect to see MAP orders by default. That is, if I subscribe to ZRX contractAddress (not assetData) and WETH contractAddress I probably don't want `ZRX/MAP(WETH,DAI,USDC)` order updates. Our subscription opts are pretty open. This is an assumption of course.

My current thinking is that we only include MAP orders when the MAP `assetProxyId` is set. ERC20,ERC721,ERC1155 are all ok because a contractAddress can't really be both/contain multiple. 

```
makerContractAddress
takerContractAddress
traderAddress
```
The above are all a bit ambiguous. 

```
# Return any orders which involve WETH in MAP and ZRX ERC20
makerAssetProxyId: ERC20
takerAssetProxyId: MAP
makerContractAddress: ZRX
takerContractAddress: WETH
```

There's a lot of permutations since we defined all arguments as optional.

2019-07-29 02:36 UTC, dekz commented on ts/src/websocket.ts
> +        ws.send(err.message);
Updated to return JSON errors in the same way our HTTP handlers do (without http status code)

2019-07-29 02:51 UTC, dekz commented on ts/src/websocket.ts
> +        // takerAssetProxyId?: string;
Yes for handling MAP.

2019-08-01 07:56 UTC, merged