V3
0xProject/0x-launch-kit-backend pull request #76
Opened 2019-10-16 01:10 UTC by dekz

2019-10-17 01:49 UTC, fragosti commented on ts/src/config.ts
> +    ? 'ws://localhost:60557'
what happens if 'ws://localhost:60557' isn't running a mesh node?

2019-10-17 01:49 UTC, fragosti commented on ts/src/mesh_utils.ts
> +const d = require('debug')('MESH');
What is this? Maybe a comment?

2019-10-17 01:49 UTC, fragosti commented on ts/src/runners/http_service_runner.ts
> +(async () => {
This is a cool pattern! (the service and service running, but also the monolith). Does this have something to do with how we plan on deploying?

2019-10-17 01:49 UTC, fragosti commented on ts/src/services/orderbook_service.ts
> +            takerAddress: ordersFilterParams.takerAddress,
Should the fee asset datas be in here too?

2019-10-17 01:49 UTC, fragosti commented on ts/src/services/orderbook_service.ts
> +        // Order Watcher Service will handle persistence
My understanding from the ENV var is that Mesh is optional, but here it seems that to POST /order we need Mesh. Is that correct? I know that we don't want to run persist orders unless they're on Mesh but launch-kit should support no mesh right?

2019-10-17 01:49 UTC, fragosti commented on ts/src/types.ts
> +    traderAssetData?: string;
fee asset data

2019-10-17 03:10 UTC, dekz commented on ts/src/runners/http_service_runner.ts
> +(async () => {
We may want to scale the HTTP/WS without scaling Mesh writes to the DB.

Unknown the demand of HTTP compared to WS at this stage. HTTP only needs to post to Mesh, whereas WS requires a constant connection to Mesh.

There should only be 1 writer to the db to prevent collisions/inconsistencies/duplicate work.

2019-10-17 03:11 UTC, dekz commented on ts/src/services/orderbook_service.ts
> +        // Order Watcher Service will handle persistence
Ooops, Mesh is no longer optional so will fix that misleading comment.

Mesh is now a requirement in Launch-kit.

2019-10-17 03:16 UTC, dekz commented on ts/src/types.ts
> +    traderAssetData?: string;
Is this a supported option for websocket? Doesn't appear in our [JSON Schema](https://github.com/0xProject/0x-monorepo/blob/3.0/packages/json-schemas/schemas/relayer_api_orders_channel_subscribe_payload_schema.json#L4)

2019-10-17 03:21 UTC, dekz commented on ts/src/config.ts
> +    ? 'ws://localhost:60557'
This is now mandatory. Updated comment

2019-10-17 03:48 UTC, fabioberger requested changes

2019-10-17 03:48 UTC, fabioberger commented on ormconfig.json
> +    "logger": "debug",
Do we want to commit this? Was it removed before we made the Docker image?

2019-10-17 03:48 UTC, fabioberger commented on package.json
> +    "description": "0x Relayer",
```suggestion
    "description": "Template 0x relayer",
```

2019-10-17 03:48 UTC, fabioberger commented on ts/src/config.ts
> +// Mesh Endpoint. Optional
```suggestion
// Mesh Endpoint
```

2019-10-17 03:48 UTC, fabioberger commented on ts/src/config.ts
> +    : assertEnvVarType('MAKER_FEE_ASSET_DATA', process.env.MAKER_FEE_UNIT_AMOUNT, EnvVarType.FeeAssetData);
```suggestion
    : assertEnvVarType('MAKER_FEE_ASSET_DATA', process.env.MAKER_ASSET_DATA, EnvVarType.FeeAssetData);
```

2019-10-17 03:48 UTC, fabioberger commented on ts/src/config.ts
> +    : assertEnvVarType('TAKER_FEE_ASSET_DATA', process.env.TAKER_FEE_UNIT_AMOUNT, EnvVarType.FeeAssetData);
```suggestion
    : assertEnvVarType('TAKER_FEE_ASSET_DATA', process.env.TAKER_FEE_ASSET_DATA, EnvVarType.FeeAssetData);
```

2019-10-17 03:48 UTC, fabioberger commented on ts/src/errors.ts
> +}
If this isn't being used, let's remove it and add it once it's needed. Avoid dead code.

2019-10-17 03:48 UTC, fabioberger commented on ts/src/models/SignedOrderModel.ts
>      }
What about `ChainID`? Sometimes the same `exchangeAddress` exists on multiple networks.

2019-10-17 03:48 UTC, fabioberger commented on ts/src/services/order_watcher_service.ts
> +                await connection.manager.save(signedOrdersModel);
If we receive an `updated` event for an order that was previously removed from the DB, we want to noop, not re-add it. We need to handle `updated` differently to `added` here to achieve this behavior. Right now, the order will get re-added.

Example: Order is considered expired according to UTC. We remove it from DB. We later receive a `FILLED` event for this order. We don't care about the fill because we've already dropped the order. The logic as currently written would cause the UTC expired order to get re-added.

2019-10-17 03:48 UTC, fabioberger commented on ts/src/services/order_watcher_service.ts
> +        // Remove all of the rejected orders
You should not remove orders that have been rejected with errors `EthRPCRequestFailed`, `CoordinatorRequestFailed`, `CoordinatorEndpointNotFound`, `InternalError`. Ideally we'd retry adding these at a later date. Do you want to keep this as an outstanding TODO? If so, let's add a `// TODO(dekz):` comment about it here.

2019-10-17 03:48 UTC, fabioberger commented on ts/src/services/order_watcher_service.ts
> +        const orders = await getOrdersPromise;
```suggestion
        const orders = await this._meshClient.getOrdersAsync();
```

2019-10-17 03:48 UTC, fabioberger commented on ts/src/services/websocket_service.ts
> +            // do nothing
Let's make this a TODO comment to eventually add support for `StaticCall` assetData.

2019-10-17 03:48 UTC, fabioberger commented on ts/src/services/websocket_service.ts
> +        this._meshClient.subscribeToOrdersAsync(e => this.orderUpdate(MeshUtils.orderInfosToApiOrders(e)));
We should store the `subscriptionId` returned from Mesh and also `unsubscribeAsync()` in `destroy`

2019-10-17 03:48 UTC, fabioberger commented on ts/src/services/websocket_service.ts
> +            // to have many subscribers and a single order
Mesh will only ever return a single OrderEvent per order so your conjecture is correct here. We should invert this map.

2019-10-17 05:05 UTC, dekz commented on ormconfig.json
> +    "logger": "debug",
This isn't enabling debug logging, it is using `debug` npm package as the logger. 

So you can start the service with `DEBUG=typeorm:*` to get TypeORM logging, or `DEBUG=express:*` to get Express logging. Similarly `DEBUG=mesh` for mesh logging, `DEBUG=*` for all.

I'd be open to change this to a log format and transport that is best for our infratructure.

2019-10-17 05:09 UTC, dekz commented on ts/src/services/order_watcher_service.ts
> +        // Remove all of the rejected orders
`EthRPCRequestFailed` `InternalError` are useless to `backend`. Ideally the `mesh-rpc-client` would handle this in the correct way no? 

Backend can't keep them because they could be expired or fully filled.

2019-10-17 05:10 UTC, dekz commented on ts/src/services/websocket_service.ts
> +            // do nothing
How would we handle `StaticCall`?

2019-10-17 21:01 UTC, fragosti commented on ts/src/services/orderbook_service.ts
> +        // Order Watcher Service will handle persistence
Ok so implementation wise this makes sense now. Did product approve launch-kit being dependent on mesh?

2019-10-17 21:04 UTC, fragosti commented on ts/src/types.ts
> +    traderAssetData?: string;
No you're right I didn't add them to reduce the complexity of implementing the websocket endpoint.

2019-10-17 21:07 UTC, fragosti commented on ts/src/services/order_watcher_service.ts
> +        const orders = await getOrdersPromise;
I think this was a perf optimization?

2019-10-17 23:29 UTC, fragosti reviewed
Just wanted to clarify. We now have a hard dependency on mesh to run launch-kit, right? Should we add that to the README or provide some sort of docker-compose entry-point?

2019-10-18 08:17 UTC, dekz commented on ts/src/services/order_watcher_service.ts
> +                await connection.manager.save(signedOrdersModel);
discussed `endState` and this case should be handled.

2019-10-18 08:45 UTC, dekz commented on ts/src/models/SignedOrderModel.ts
>      }
This is being calculated by the passed in `NETWORK_ID`. We do not have an RPC URL anymore as we are reliant on Mesh for all the Ethereum network related requests. 

Let's think about this some more from the internal discussions as well given that the Exchange ChainID may not always reflect the realised chainId

2019-10-18 08:46 UTC, dekz commented
> Just wanted to clarify. We now have a hard dependency on mesh to run launch-kit, right? Should we add that to the README or provide some sort of docker-compose entry-point?

Most definitely, launch-kit-wizard will need to be updated to deploy a Mesh node by default. README will be updated soon.

2019-10-18 16:08 UTC, fragosti approved these changes

2019-10-18 17:10 UTC, fragosti commented on ts/src/types.ts
> +export interface OrderChannelRequest {
Are these not in @0x/connect?

2019-10-19 02:42 UTC, fragosti commented on ts/src/services/http_service.ts
> +         * http://sra-spec.s3-website-us-east-1.amazonaws.com/#operation/getAssetPairs
```suggestion
         * http://sra3-spec.s3-website-us-east-1.amazonaws.com/#operation/getAssetPairs
```

2019-10-19 04:33 UTC, dekz commented on ts/src/types.ts
> +export interface OrderChannelRequest {
They are now, Thanks!

https://github.com/0xProject/0x-monorepo/commit/3724ac4b675a87a3c812deea0e1ae695defe86ec

2019-10-22 20:05 UTC, fabioberger commented on ts/src/services/websocket_service.ts
> +            // do nothing
Not sure, we'd have to think it through.

2019-10-22 20:07 UTC, fabioberger approved these changes

2019-12-04 21:08 UTC, merged