Re-implement the asset pairs endpoint
0xProject/0x-launch-kit-backend pull request #9
Opened 2018-11-15 15:10 UTC by LogvinovLeon

Remove the ASSET_PAIRS config.
Generate the asset_pairs endpoint results from the orders.
Introduce the WHITELISTED_ADDRESSES config variable.
Check the incoming orders against the WHITELISTED_ADDRESSES config variable.

2018-11-15 15:29 UTC, fabioberger commented on ts/src/config.ts
> +// Whitelisted token addresses. Set to a '*' instead of an array to allow any token.
```suggestion
// Whitelisted token addresses. Set to a '*' instead of an array to allow all tokens.
```

2018-11-15 15:29 UTC, fabioberger commented on ts/src/config.ts
> +export const WHITELISTED_TOKENS: string[] | '*' = [];
Default to WETH and ZRX, since it's on testnet.

2018-11-15 19:23 UTC, fragosti commented on ts/src/config.ts
> +export const WHITELISTED_TOKENS: string[] | '*' = [
Should we allow for blacklist functionality too somehow? I agree that if we can only have one or the other, whitelist is the way to go

2018-11-15 19:23 UTC, fragosti commented on ts/src/orderbook.ts
> +        const assetPairsItems: AssetPairsItem[] = signedOrderModels.map(deserializeOrder).map(signedOrderToAssetPair);
Is the framework smart about chained maps? Might be worth just composing the functions? Not sure how much we're optimizing for perf here.

2018-11-15 19:23 UTC, fragosti commented on ts/src/orderbook.ts
> +            nonPaginatedFilteredAssetPairs = assetPairsItems.filter(containsAssetData);
Radars API actually has interesting properties that we should discuss whether we want to have be the same here:
"https://api.radarrelay.com/0x/v2/asset_pairs?**assetDataB=X**" produces the same response as " https://api.radarrelay.com/0x/v2/asset_pairs?**assetDataA=X**". 
Also 
"https://api.radarrelay.com/0x/v2/asset_pairs?**assetDataB=X&assetDataA=Y**" produces the same response as "https://api.radarrelay.com/0x/v2/asset_pairs?**assetDataA=X&assetDataB=Y**"

The first case is weird since they do it by pretending that the first query is the second query basically (if you only specify 1, it means assetDataA). However, I do like the consistency when using `assetDataA` -- you'll never see `assetDataA` from the query in `assetDataB.assetData` in the response, whereas I think you would see that in this implementation. 

I also think we return symmetric pairs, do we want that?

Whatever we decide makes most sense, we should specify in SRA :P

2018-11-15 23:36 UTC, fabioberger commented on ts/src/config.ts
> +export const WHITELISTED_TOKENS: string[] | '*' = [
Think the idea is that Launch kit is bare-bones and if someone wants something more custom, they can add it themselves.

2018-11-15 23:40 UTC, fabioberger requested changes

2018-11-15 23:40 UTC, fabioberger commented on package.json
> +        "shx": "^0.3.2",
Hm, isn't this in a separate PR?

2018-11-15 23:40 UTC, fabioberger commented on ts/src/orderbook.ts
> +                    : erc721AssetDataToAsset(assetData);
Let's make this a switch statement. Eventually we will support other assetTypes, and I want this to fail loudly if we forget to add special handling logic here for the new asset type.

2018-11-16 13:47 UTC, LogvinovLeon commented on ts/src/config.ts
> +export const WHITELISTED_TOKENS: string[] | '*' = [
I also feel that whitelisting holds less legal risk than blacklisting

2018-11-16 13:48 UTC, LogvinovLeon commented on ts/src/orderbook.ts
> +        const assetPairsItems: AssetPairsItem[] = signedOrderModels.map(deserializeOrder).map(signedOrderToAssetPair);
We're not optimizing for perf here. We have bigger problems in perf. Sqlite, inefficient queries, etc. Our assumption was that they'll have up to 10k-100k orders max and wit those numbers you can do whatever.

2018-11-16 14:25 UTC, LogvinovLeon commented on ts/src/orderbook.ts
> +            nonPaginatedFilteredAssetPairs = assetPairsItems.filter(containsAssetData);
I think this implementation is consistent with the SRA definition. If we happen to have a new version of SRA with more strict requirements in future - I'm happy to update it to meet them.

2018-11-16 14:26 UTC, merged